<a href="https://colab.research.google.com/github/AsyaKarpova/EduMatches/blob/main/m_try.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#!pip install sentence_transformers

In [ ]:
import pandas as pd
import numpy as np
import sklearn

from sentence_transformers import SentenceTransformer
import scipy.spatial

In [ ]:
embedder = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [ ]:
df = pd.read_excel('hidden.xlsx')[1:]

In [ ]:
topics = df['lesson_topic'].dropna().drop_duplicates().tolist()

In [ ]:
topics_emb = embedder.encode(topics)

In [ ]:
topics_emb.shape

(368, 768)

In [ ]:
topics_emb

array([[ 0.05150623, -0.06089226,  1.3475062 , ...,  0.07011548,
         0.44792914,  0.27081516],
       [-0.59102756,  0.30314904,  0.968374  , ..., -0.08592685,
         0.22766472,  0.39517668],
       [-0.07462175,  0.23871264,  1.2214429 , ..., -0.11695416,
         0.28085884,  0.30615926],
       ...,
       [-0.22180583,  0.04385905,  0.7535241 , ..., -0.42903104,
         0.32486162,  0.16067347],
       [-0.7251423 ,  0.17265871,  1.0186237 , ..., -0.15251406,
         0.32781595,  0.49416462],
       [-0.4082483 ,  0.22695224,  0.93720603, ..., -0.2166171 ,
         0.3688548 ,  0.21490987]], dtype=float32)

In [ ]:
#!apt-get install libomp-dev
#!pip install faiss

import faiss

In [ ]:
d= 768
index = faiss.IndexFlatL2(d)
index.add(np.stack(topics_emb, axis=0))
print(index.ntotal)

368


In [ ]:
#query = ['hidden']

In [ ]:
query_emb = embedder.encode(query)

In [ ]:
k = 5                         
D, I = index.search(np.stack(query_emb, axis=0), k)  

In [ ]:
D

array([[15.236668, 15.741095, 16.611603, 16.765608, 17.076954]],
      dtype=float32)

In [ ]:
I

array([[361, 293, 348, 204, 258]])

In [ ]:
for query, query_embedding in zip(query, query_emb):
    distances, indices = index.search(np.asarray(query_embedding).reshape(1,768), k)
    print("Query:", query)
    print("\n")
    for idx in range(0,5):
        print(topics[indices[0, idx]])

In [ ]:
query